remote_theme: jekyll/minima

title: Nickykatt

description: Product management, digital health and NHS transformation © 2020–2026 Nicholas Katz. All rights reserved.

author: Nicholas Katz

show_excerpts: true

header_pages:
  - about.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: dark

  social_links:
    - title: Nickykatt repository at GitHub
      icon: github
      url: https://github.com/nickykatt/
    - title: Nick at LinkedIn
      icon: linkedin-in
      url: https://www.linkedin.com/in/nick-katz/

